### ISSUE TITLE
Getting Python Error -- TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by yaitorr** [ggordan/GutterColor#118]
Hi there,
I recently installed the GutterColor ST3 plugin and I'm getting the following exception in the console, every time the plugin tries to run:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/yaisiel.torres/Library/Application Support/Sublime Text 3/Packages/Gutter Color/gutter_color.py", line 40, in on_activated_async
    if syntax(view) in settings().get('supported_syntax'):
TypeError: argument of type 'NoneType' is not iterable
```

I already validated that I have the right ImageMagick install and ran all the ImageMagic-related troubleshooting in this repo's README. Am I still missing something from the install? Please let me know if you need additional details!

**Comment by ocket8888** [comment]
Looks like the issue is the default value of the `supported_syntax` key not getting set properly. If you open the command palette (<kbd>Ctrl</kbd>+<kbd>P</kbd> on good operating systems, <kbd>Cmd</kbd>+<kbd>P</kbd> on Macs) and add:
```json
{
	"supported_syntax": [
		"css",
		"scss",
		"sass",
		"less",
		"stylus",
		"css3",
		"xml"
	]
}
```
(which mimicks the defaults) that error message goes away. Of course, now I'm seeing a different error....

**Comment by mazunki** [comment]
I had this problem too. It worked after removing the package and reinstalling it.
