### ISSUE TITLE
[ST3 3095] Errors after installing through package control

### ISSUE THREAD

**Issue by olimorris** [ggordan/GutterColor#88]
After installing ImageMagick just fine and installing GutterColor through package control, I get the following errors in ST3:

```
reloading plugin Gutter Color.file
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/file.py", line 3, in <module>
    from .line import Line
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.gutter_color
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/gutter_color.py", line 1, in <module>
    from .file import File
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/file.py", line 3, in <module>
    from .line import Line
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.line
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.webcolors
```

**Comment by jbrooksuk** [comment]
Doh.

**Comment by jbrooksuk** [comment]
I'll have to fix this later I'm afraid.

**Comment by jbrooksuk** [comment]
Can you try the master copy please? Just pushed a fix.

**Comment by olimorris** [comment]
Still getting pretty much the same error, except:
```
  File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/line.py", line 4, in <module>
    from GutterColor import webcolors
```
is now replaced by:
```
File "/Users/Oli/Library/Application Support/Sublime Text 3/Packages/Gutter Color/line.py", line 4, in <module>
    from .webcolors import webcolors
```

**Comment by SecureCloud-biz** [comment]
i too am getting an error, please push a fix. [i installed thru package control awhile ago, no problems until recently]

here's my dump:

```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/_______Sublime_Text_x64/sublime_text.exe
working dir: /C/_______Sublime_Text_x64
packages path: /C/_______Sublime_Text_x64/Data/Packages
state path: /C/_______Sublime_Text_x64/Data/Local
zip path: /C/_______Sublime_Text_x64/Packages
zip path: /C/_______Sublime_Text_x64/Data/Installed Packages
ignored_packages: ["Goto Bootstrap", "EasyDiff", "CSS Extended Completions", "JavaScript", "C++", "Vintage", "ASP", "ScopeHunter", "Nodejs", "C#", "AppleScript"]
pre session restore time: 0.195694
startup time: 0.388694
first paint time: 0.394694
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin Better Completion.main
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Emmet.emmet-plugin
reloading plugin FileDiffs.file_diffs
reloading plugin Fold Comments.foldcomments
reloading plugin Highlighter.highlighter
reloading plugin Instacode.instacode
reloading plugin Javascript Beautify.jsbeautify
reloading plugin JavaScript Ultimate.install
reloading plugin jQueryDocs.jQueryDocs
reloading plugin JsFormat.js_formatter
reloading plugin JSON Reindent.json_reindent
reloading plugin JSONLint.JSONLint
reloading plugin LESS.less_completions
reloading plugin Less2Css.less2css
reloading plugin Less2Css.lesscompiler
reloading plugin List LESS Variables.lessvariables
reloading plugin List stylesheet variables.stylevariables
reloading plugin LogView.logview
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin PHP Companion.PHP Companion
reloading plugin PhpNamespace.classes
reloading plugin PhpNamespace.namespaces
reloading plugin PhpNamespace.PhpNamespaceCopy
reloading plugin PhpNamespace.utils
reloading plugin SideBarFolders.SideBarFolders
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin Stupid Indent.stupid_indent
reloading plugin SublimeLinter-contrib-bootlint.linter
SublimeLinter: bootlint linter loaded 
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin Gutter Color.file                                                      <<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "C:\_______Sublime_Text_x64\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\file.py", line 3, in <module>
    from .line import Line
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.gutter_color
Traceback (most recent call last):
  File "C:\_______Sublime_Text_x64\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\gutter_color.py", line 1, in <module>
    from .file import File
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\file.py", line 3, in <module>
    from .line import Line
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.line
Traceback (most recent call last):
  File "C:\_______Sublime_Text_x64\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\_______Sublime_Text_x64\Data\Packages\Gutter Color\line.py", line 4, in <module>
    from GutterColor import webcolors
ImportError: No module named 'GutterColor'
reloading plugin Gutter Color.webcolors
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
CodeFormatter: Plugin Initialized
Emmet: No need to update PyV8
Package Control: No updated packages
```

**Comment by jbrooksuk** [comment]
Should be fixed in https://github.com/ggordan/GutterColor/releases/tag/v0.3.2

**Comment by olimorris** [comment]
Yep happy to report 0.3.2 fixes the issues. Thanks

**Comment by jbrooksuk** [comment]
Awesome :)
